(add-to-list 'auto-mode-alist '("\\.automount\\'" . conf-unix-mode))
(add-to-list 'auto-mode-alist '("\\.bash\\'" . sh-mode))
(add-to-list 'auto-mode-alist '("\\.link\\'" . conf-unix-mode))
(add-to-list 'auto-mode-alist '("\\.mount\\'" . conf-unix-mode))
(add-to-list 'auto-mode-alist '("\\.netdev\\'" . conf-unix-mode))
(add-to-list 'auto-mode-alist '("\\.network\\'" . conf-unix-mode))
(add-to-list 'auto-mode-alist '("\\.path\\'" . conf-unix-mode))
(add-to-list 'auto-mode-alist '("\\.service\\'" . conf-unix-mode))
(add-to-list 'auto-mode-alist '("\\.slice\\'" . conf-unix-mode))
(add-to-list 'auto-mode-alist '("\\.socket\\'" . conf-unix-mode))
(add-to-list 'auto-mode-alist '("\\.target\\'" . conf-unix-mode))
(add-to-list 'auto-mode-alist '("\\.timer\\'" . conf-unix-mode))
(add-to-list 'auto-mode-alist '("\\.zsh\\'" . sh-mode))
(blink-cursor-mode -1)
(column-number-mode 1)
(delete-selection-mode 1)
(electric-indent-mode 1)
(electric-pair-mode 1)
(fset 'yes-or-no-p 'y-or-n-p)
(global-auto-revert-mode 1)
(menu-bar-mode -1)
(prefer-coding-system 'utf-8)
(put 'downcase-region 'disabled nil)
(put 'erase-buffer 'disabled nil)
(put 'eval-expression 'disabled nil)
(put 'narrow-to-page 'disabled nil)
(put 'narrow-to-region 'disabled nil)
(put 'set-goal-column 'disabled nil)
(put 'upcase-region 'disabled nil)
(recentf-mode -1)
(set-charset-priority 'unicode)
(set-default-coding-systems 'utf-8)
(set-keyboard-coding-system 'utf-8)
(set-selection-coding-system 'utf-8)
(set-terminal-coding-system 'utf-8)
(setq auto-revert-verbose nil)
(setq auto-save-default nil)
(setq case-fold-search nil)
(setq current-language-environment "UTF-8")
(setq default-buffer-file-coding-system 'utf-8)
(setq default-process-coding-system '(utf-8-unix . utf-8-unix))
(setq echo-keystrokes 0.01)
(setq global-auto-revert-non-file-buffers t)
(setq inhibit-startup-echo-area-message t)
(setq inhibit-startup-message t)
(setq initial-major-mode 'emacs-lisp-mode)
(setq initial-scratch-message "")
(setq jit-lock-defer-time 0.05)
(setq locale-coding-system 'utf-8)
(setq mouse-wheel-progressive-speed nil)
(setq mouse-wheel-scroll-amount '(0.05))
(setq redisplay-dont-pause t)
(setq ring-bell-function 'ignore)
(setq scroll-margin 3)
(setq scroll-preserve-screen-position t)
(setq show-paren-delay 0)
(setq show-trailing-whitespace t)
(setq x-select-request-type '(UTF8_STRING COMPOUND_TEXT TEXT STRING))
(setq-default fill-column 80)
(setq-default indent-tabs-mode nil)
(setq-default tab-stop-list (number-sequence 4 120 4))
(setq-default tab-width 4)
(setq-default truncate-lines nil)
(show-paren-mode 1)
(size-indication-mode 1)
(tooltip-mode -1)
(transient-mark-mode 1)
(which-function-mode -1)
(xterm-mouse-mode 1)

;; make scrolling very laggy:
;(global-hl-line-mode 1)
;(global-linum-mode 1)
;(global-prettify-symbols-mode 1)
;(visual-line-mode 1)
